/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok3.app.pasien;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fauza
 */
public class kamar extends javax.swing.JFrame {
    boolean sidePaneHidden = false;

    /**
     * Creates new form kamar
     */
    
    public void showTablePasien() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("id_pasien");
        tb.addColumn("nama_pasien");        
        try {
            String query = "SELECT id_pasien, nama_pasien FROM pasien";
            java.sql.Connection conn=(Connection)DBconnection.configDB();
            java.sql.Statement s = conn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            while (r.next()){
                tb.addRow(new Object[]{
                    r.getString(1),r.getString(2)
                });
            }
            tabel_pasien.setModel(tb);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    
    
    public void showTableKamar() {
    DefaultTableModel tb = new DefaultTableModel();
    tb.addColumn("kode_kamar");
    tb.addColumn("id_pasien");
    tb.addColumn("status");
        try {
            String query = "SELECT * FROM kamar";
            java.sql.Connection conn=(Connection)DBconnection.configDB();
            java.sql.Statement s = conn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            while (r.next()){
                tb.addRow(new Object[]{
                    r.getString(1),r.getString(2),r.getString(3)
                });
            }
            tabel_kamar.setModel(tb);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clean(){
        in_kamar.setText(null);
        in_pasien.setText(null);
    }
    
    public kamar() {
        initComponents();
        showTableKamar();
        showTablePasien();
        clean();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        itemSidebar3 = new javax.swing.JPanel();
        iconDokter = new javax.swing.JLabel();
        labelMenu3 = new javax.swing.JLabel();
        itemSidebar1 = new javax.swing.JPanel();
        iconPasien = new javax.swing.JLabel();
        labelMenu1 = new javax.swing.JLabel();
        itemSidebar0 = new javax.swing.JPanel();
        iconTitle = new javax.swing.JLabel();
        labelMenu0 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        itemSidebar2 = new javax.swing.JPanel();
        iconKamar = new javax.swing.JLabel();
        labelMenu2 = new javax.swing.JLabel();
        itemSidebar4 = new javax.swing.JPanel();
        iconAdmin = new javax.swing.JLabel();
        labelMenu4 = new javax.swing.JLabel();
        itemSidebar5 = new javax.swing.JPanel();
        iconAdmin1 = new javax.swing.JLabel();
        labelMenu5 = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();
        in_kamar = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        labelSpesialis = new javax.swing.JLabel();
        in_pasien = new javax.swing.JTextField();
        b_tambah = new javax.swing.JButton();
        b_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kamar = new javax.swing.JTable();
        in_status = new javax.swing.JComboBox<>();
        labelSpesialis1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_pasien = new javax.swing.JTable();
        b_hapus = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(35, 40, 44));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(21, 25, 28));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemSidebar3.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar3MouseClicked(evt);
            }
        });

        iconDokter.setBackground(new java.awt.Color(21, 25, 28));
        iconDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_stethoscope_16px.png"))); // NOI18N
        iconDokter.setOpaque(true);

        labelMenu3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu3.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu3.setText("Data Dokter");

        javax.swing.GroupLayout itemSidebar3Layout = new javax.swing.GroupLayout(itemSidebar3);
        itemSidebar3.setLayout(itemSidebar3Layout);
        itemSidebar3Layout.setHorizontalGroup(
            itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar3Layout.setVerticalGroup(
            itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 80));

        itemSidebar1.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar1MouseClicked(evt);
            }
        });

        iconPasien.setBackground(new java.awt.Color(21, 25, 28));
        iconPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_wheelchair_16px.png"))); // NOI18N
        iconPasien.setOpaque(true);

        labelMenu1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu1.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu1.setText("Data Pasien");

        javax.swing.GroupLayout itemSidebar1Layout = new javax.swing.GroupLayout(itemSidebar1);
        itemSidebar1.setLayout(itemSidebar1Layout);
        itemSidebar1Layout.setHorizontalGroup(
            itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        itemSidebar1Layout.setVerticalGroup(
            itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        itemSidebar0.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar0MouseClicked(evt);
            }
        });

        iconTitle.setBackground(new java.awt.Color(21, 25, 28));
        iconTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_hospital_32px.png"))); // NOI18N
        iconTitle.setOpaque(true);

        labelMenu0.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelMenu0.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu0.setText("Pasien-App");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout itemSidebar0Layout = new javax.swing.GroupLayout(itemSidebar0);
        itemSidebar0.setLayout(itemSidebar0Layout);
        itemSidebar0Layout.setHorizontalGroup(
            itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar0Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        itemSidebar0Layout.setVerticalGroup(
            itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar0Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePane.add(itemSidebar0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        itemSidebar2.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        iconKamar.setBackground(new java.awt.Color(54, 79, 205));
        iconKamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_bed_16px_9.png"))); // NOI18N
        iconKamar.setOpaque(true);

        labelMenu2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        labelMenu2.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu2.setText("Data Kamar");

        javax.swing.GroupLayout itemSidebar2Layout = new javax.swing.GroupLayout(itemSidebar2);
        itemSidebar2.setLayout(itemSidebar2Layout);
        itemSidebar2Layout.setHorizontalGroup(
            itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar2Layout.setVerticalGroup(
            itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        itemSidebar4.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar4MouseClicked(evt);
            }
        });

        iconAdmin.setBackground(new java.awt.Color(21, 25, 28));
        iconAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_microsoft_admin_16px.png"))); // NOI18N
        iconAdmin.setOpaque(true);

        labelMenu4.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu4.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu4.setText("Data Admin");

        javax.swing.GroupLayout itemSidebar4Layout = new javax.swing.GroupLayout(itemSidebar4);
        itemSidebar4.setLayout(itemSidebar4Layout);
        itemSidebar4Layout.setHorizontalGroup(
            itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar4Layout.setVerticalGroup(
            itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        itemSidebar5.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar5MouseClicked(evt);
            }
        });

        iconAdmin1.setBackground(new java.awt.Color(21, 25, 28));
        iconAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shutdown_16px.png"))); // NOI18N
        iconAdmin1.setOpaque(true);

        labelMenu5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu5.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu5.setText("Logout");

        javax.swing.GroupLayout itemSidebar5Layout = new javax.swing.GroupLayout(itemSidebar5);
        itemSidebar5.setLayout(itemSidebar5Layout);
        itemSidebar5Layout.setHorizontalGroup(
            itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar5Layout.setVerticalGroup(
            itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        background.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 660));

        contentPane.setBackground(new java.awt.Color(35, 40, 44));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        in_kamar.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.add(in_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 39));

        labelNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Kode Kamar");
        contentPane.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        labelSpesialis.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis.setText("Status");
        contentPane.add(labelSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        in_pasien.setEditable(false);
        in_pasien.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.add(in_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 39));

        b_tambah.setBackground(new java.awt.Color(21, 25, 28));
        b_tambah.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        b_tambah.setForeground(new java.awt.Color(255, 255, 255));
        b_tambah.setText("Tambah");
        b_tambah.setBorder(null);
        b_tambah.setOpaque(true);
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });
        contentPane.add(b_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 109, 49));

        b_edit.setBackground(new java.awt.Color(21, 25, 28));
        b_edit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        b_edit.setForeground(new java.awt.Color(255, 255, 255));
        b_edit.setText("Ubah");
        b_edit.setBorder(null);
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });
        contentPane.add(b_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 109, 49));

        jScrollPane1.setBackground(new java.awt.Color(35, 40, 44));
        jScrollPane1.setBorder(null);

        tabel_kamar.setForeground(new java.awt.Color(0, 0, 0));
        tabel_kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "kode_kamar", "id_pasien", "status"
            }
        ));
        tabel_kamar.setToolTipText("");
        tabel_kamar.setOpaque(false);
        tabel_kamar.setSelectionForeground(new java.awt.Color(21, 25, 28));
        tabel_kamar.setShowGrid(true);
        tabel_kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kamar);
        if (tabel_kamar.getColumnModel().getColumnCount() > 0) {
            tabel_kamar.getColumnModel().getColumn(0).setHeaderValue("kode_kamar");
        }

        contentPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 450, 210));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(35,40,44));

        in_status.setBackground(new java.awt.Color(255, 255, 255));
        in_status.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        in_status.setForeground(new java.awt.Color(21, 25, 28));
        in_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Penuh" }));
        contentPane.add(in_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, 40));

        labelSpesialis1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis1.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis1.setText("Id Pasien");
        contentPane.add(labelSpesialis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(35, 40, 44));
        jScrollPane2.setBorder(null);

        tabel_pasien.setForeground(new java.awt.Color(0, 0, 0));
        tabel_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "id_pasien", "nama_pasien"
            }
        ));
        tabel_pasien.setToolTipText("");
        tabel_pasien.setOpaque(false);
        tabel_pasien.setSelectionForeground(new java.awt.Color(21, 25, 28));
        tabel_pasien.setShowGrid(true);
        tabel_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_pasien);

        contentPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 450, 310));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(35,40,44));

        b_hapus.setBackground(new java.awt.Color(21, 25, 28));
        b_hapus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(255, 255, 255));
        b_hapus.setText("Hapus");
        b_hapus.setBorder(null);
        b_hapus.setOpaque(true);
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });
        contentPane.add(b_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 110, 50));

        b_clear.setBackground(new java.awt.Color(21, 25, 28));
        b_clear.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        b_clear.setForeground(new java.awt.Color(255, 255, 255));
        b_clear.setText("Clear");
        b_clear.setBorder(null);
        b_clear.setOpaque(true);
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });
        contentPane.add(b_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 110, 50));

        background.add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 820, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemSidebar0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar0MouseClicked
        // 200
        if(sidePaneHidden == false) {
            sidePane.setBounds(sidePane.getX(), sidePane.getY(), 72, sidePane.getHeight());
            contentPane.setBounds(contentPane.getX() - 72, contentPane.getY(), contentPane.getWidth() + 72 , contentPane.getHeight());
            sidePaneHidden = true;
        }
        else {
            sidePane.setBounds(sidePane.getX(), sidePane.getY(), 200, sidePane.getHeight());
            contentPane.setBounds(contentPane.getX() + 72, contentPane.getY(), contentPane.getWidth() - 72 , contentPane.getHeight());
            sidePaneHidden = false;
        }
    }//GEN-LAST:event_itemSidebar0MouseClicked

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        if(in_kamar.equals("")){
            JOptionPane.showMessageDialog(null, "kode_kamar tidak boleh kosong");
        }else{
            try {
                String sql = "INSERT INTO kamar VALUES ('"+in_kamar.getText()+"','"+in_pasien.getText()+"','"+in_status.getSelectedItem()+"')";
                java.sql.Connection conn=(Connection)DBconnection.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                showTableKamar();
                showTablePasien();
                clean();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed
        String kamar = in_kamar.getText();
        String pasien = in_pasien.getText();
        String status = (String) in_status.getSelectedItem();
        if(in_kamar.equals("")){
            JOptionPane.showMessageDialog(null, "kode_kamar tidak boleh kosong");
        }else{
            try{
                String query = "UPDATE kamar SET kode_kamar = '"+kamar+"', id_pasien = "+pasien+", status = '"+status+"' WHERE kode_kamar = '"+kamar+"'";
                Connection conn = (Connection)DBconnection.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(query);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                showTableKamar();
                showTablePasien();
                clean();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }   
        }
    }//GEN-LAST:event_b_editActionPerformed

    private void tabel_kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kamarMouseClicked
        int baris = tabel_kamar.rowAtPoint(evt.getPoint());
        String kamar = tabel_kamar.getValueAt(baris, 0).toString();
        in_kamar.setText(kamar);
        String pasien = tabel_kamar.getValueAt(baris, 1).toString();
        in_pasien.setText(pasien);
        String status = tabel_kamar.getValueAt(baris, 2).toString();
        in_status.setSelectedItem(status);
    }//GEN-LAST:event_tabel_kamarMouseClicked

    private void tabel_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pasienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_pasienMouseClicked

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        String kamar = in_kamar.getText();
        String pasien = in_pasien.getText();
        String status = (String) in_status.getSelectedItem();
        try {
            String query = "DELETE FROM kamar WHERE kode_kamar = '"+kamar+"'";
            Connection conn = (Connection)DBconnection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            showTableKamar();
            showTablePasien();
            clean();
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        clean();
    }//GEN-LAST:event_b_clearActionPerformed

    private void itemSidebar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar3MouseClicked
        new dokter().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar3MouseClicked

    private void itemSidebar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar1MouseClicked
        new pasien().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar1MouseClicked

    private void itemSidebar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar4MouseClicked
        new admin().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar4MouseClicked

    private void itemSidebar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar5MouseClicked
        new login().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar5MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_edit;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_tambah;
    private javax.swing.JPanel background;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel iconAdmin;
    private javax.swing.JLabel iconAdmin1;
    private javax.swing.JLabel iconDokter;
    private javax.swing.JLabel iconKamar;
    private javax.swing.JLabel iconPasien;
    private javax.swing.JLabel iconTitle;
    private javax.swing.JTextField in_kamar;
    private javax.swing.JTextField in_pasien;
    private javax.swing.JComboBox<String> in_status;
    private javax.swing.JPanel itemSidebar0;
    private javax.swing.JPanel itemSidebar1;
    private javax.swing.JPanel itemSidebar2;
    private javax.swing.JPanel itemSidebar3;
    private javax.swing.JPanel itemSidebar4;
    private javax.swing.JPanel itemSidebar5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMenu0;
    private javax.swing.JLabel labelMenu1;
    private javax.swing.JLabel labelMenu2;
    private javax.swing.JLabel labelMenu3;
    private javax.swing.JLabel labelMenu4;
    private javax.swing.JLabel labelMenu5;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelSpesialis;
    private javax.swing.JLabel labelSpesialis1;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable tabel_kamar;
    private javax.swing.JTable tabel_pasien;
    // End of variables declaration//GEN-END:variables
}
