/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok3.app.pasien;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fauza
 */
public class pasien extends javax.swing.JFrame {
    boolean sidePaneHidden = false;
    String id_pasien;
    
    /**
     * Creates new form pasien
     */
    public pasien() {
        initComponents();
        showTablePasien();
        showTableKamar();
        setkolom();
    }
    
    private void setkolom() {
        tbPasien.getColumnModel().getColumn(0).setMaxWidth(30);
        tbPasien.getColumnModel().getColumn(2).setMaxWidth(40);
    }
    
    private void clean(){
        txtNama.setText(null);
        txtUsia.setText(null);
        txtNoTelp.setText(null);
        txtaAlamat.setText(null);
        cboJK.setSelectedIndex(0);
    }
    
    public void showTablePasien() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Id");
        tb.addColumn("Nama");
        tb.addColumn("Usia");       
        tb.addColumn("Jenis Kelamin");        
        tb.addColumn("No Telp"); 
        tb.addColumn("Alamat");                
        try {   
            String query = "SELECT id_pasien, nama_pasien, usia, jenis_kelamin, no_telp, alamat FROM pasien";
            java.sql.Connection conn=(Connection)DBconnection.configDB();
            java.sql.Statement s = conn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            while (r.next()){
                tb.addRow(new Object[]{
                    r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)
                });
            }
            tbPasien.setModel(tb);
            setkolom();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void showTableKamar() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No Kamar");
        tb.addColumn("Status");               
        try {   
            String query = "SELECT kode_kamar, status FROM kamar WHERE status = 'Kosong'";
            java.sql.Connection conn=(Connection)DBconnection.configDB();
            java.sql.Statement s = conn.createStatement();
            java.sql.ResultSet r = s.executeQuery(query);
            while (r.next()){
                tb.addRow(new Object[]{
                    r.getString(1),r.getString(2)
                });
            }
            tbKamar.setModel(tb);
            setkolom();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        itemSidebar3 = new javax.swing.JPanel();
        iconDokter = new javax.swing.JLabel();
        labelMenu3 = new javax.swing.JLabel();
        itemSidebar1 = new javax.swing.JPanel();
        iconPasien = new javax.swing.JLabel();
        labelMenu1 = new javax.swing.JLabel();
        itemSidebar0 = new javax.swing.JPanel();
        iconTitle = new javax.swing.JLabel();
        labelMenu0 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        itemSidebar2 = new javax.swing.JPanel();
        iconKamar = new javax.swing.JLabel();
        labelMenu2 = new javax.swing.JLabel();
        itemSidebar4 = new javax.swing.JPanel();
        iconAdmin = new javax.swing.JLabel();
        labelMenu4 = new javax.swing.JLabel();
        itemSidebar5 = new javax.swing.JPanel();
        iconAdmin1 = new javax.swing.JLabel();
        labelMenu5 = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        labelSpesialis = new javax.swing.JLabel();
        txtUsia = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtKamar = new javax.swing.JTextField();
        labelCari = new javax.swing.JLabel();
        cboJK = new javax.swing.JComboBox<>();
        labelSpesialis1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtNoTelp = new javax.swing.JTextField();
        labelSpesialis2 = new javax.swing.JLabel();
        labelSpesialis3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPasien = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKamar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(35, 40, 44));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(21, 25, 28));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemSidebar3.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar3MouseClicked(evt);
            }
        });

        iconDokter.setBackground(new java.awt.Color(21, 25, 28));
        iconDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_stethoscope_16px.png"))); // NOI18N
        iconDokter.setOpaque(true);

        labelMenu3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu3.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu3.setText("Data Dokter");

        javax.swing.GroupLayout itemSidebar3Layout = new javax.swing.GroupLayout(itemSidebar3);
        itemSidebar3.setLayout(itemSidebar3Layout);
        itemSidebar3Layout.setHorizontalGroup(
            itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar3Layout.setVerticalGroup(
            itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 80));

        itemSidebar1.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar1MouseClicked(evt);
            }
        });

        iconPasien.setBackground(new java.awt.Color(54, 79, 205));
        iconPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_wheelchair_16px.png"))); // NOI18N
        iconPasien.setOpaque(true);

        labelMenu1.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        labelMenu1.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu1.setText("Data Pasien");

        javax.swing.GroupLayout itemSidebar1Layout = new javax.swing.GroupLayout(itemSidebar1);
        itemSidebar1.setLayout(itemSidebar1Layout);
        itemSidebar1Layout.setHorizontalGroup(
            itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        itemSidebar1Layout.setVerticalGroup(
            itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        itemSidebar0.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar0MouseClicked(evt);
            }
        });

        iconTitle.setBackground(new java.awt.Color(21, 25, 28));
        iconTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_hospital_32px.png"))); // NOI18N
        iconTitle.setOpaque(true);

        labelMenu0.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelMenu0.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu0.setText("Pasien-App");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout itemSidebar0Layout = new javax.swing.GroupLayout(itemSidebar0);
        itemSidebar0.setLayout(itemSidebar0Layout);
        itemSidebar0Layout.setHorizontalGroup(
            itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar0Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        itemSidebar0Layout.setVerticalGroup(
            itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar0Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePane.add(itemSidebar0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        itemSidebar2.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar2MouseClicked(evt);
            }
        });

        iconKamar.setBackground(new java.awt.Color(21, 25, 28));
        iconKamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_bed_16px_9.png"))); // NOI18N
        iconKamar.setOpaque(true);

        labelMenu2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu2.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu2.setText("Data Kamar");

        javax.swing.GroupLayout itemSidebar2Layout = new javax.swing.GroupLayout(itemSidebar2);
        itemSidebar2.setLayout(itemSidebar2Layout);
        itemSidebar2Layout.setHorizontalGroup(
            itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar2Layout.setVerticalGroup(
            itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        itemSidebar4.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar4MouseClicked(evt);
            }
        });

        iconAdmin.setBackground(new java.awt.Color(21, 25, 28));
        iconAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_microsoft_admin_16px.png"))); // NOI18N
        iconAdmin.setOpaque(true);

        labelMenu4.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu4.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu4.setText("Data Admin");

        javax.swing.GroupLayout itemSidebar4Layout = new javax.swing.GroupLayout(itemSidebar4);
        itemSidebar4.setLayout(itemSidebar4Layout);
        itemSidebar4Layout.setHorizontalGroup(
            itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar4Layout.setVerticalGroup(
            itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        itemSidebar5.setBackground(new java.awt.Color(21, 25, 28));
        itemSidebar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSidebar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSidebar5MouseClicked(evt);
            }
        });

        iconAdmin1.setBackground(new java.awt.Color(21, 25, 28));
        iconAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shutdown_16px.png"))); // NOI18N
        iconAdmin1.setOpaque(true);

        labelMenu5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelMenu5.setForeground(new java.awt.Color(255, 255, 255));
        labelMenu5.setText("Logout");

        javax.swing.GroupLayout itemSidebar5Layout = new javax.swing.GroupLayout(itemSidebar5);
        itemSidebar5.setLayout(itemSidebar5Layout);
        itemSidebar5Layout.setHorizontalGroup(
            itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemSidebar5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemSidebar5Layout.setVerticalGroup(
            itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemSidebar5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(itemSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(iconAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        sidePane.add(itemSidebar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        background.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 660));

        contentPane.setBackground(new java.awt.Color(35, 40, 44));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 39));

        labelNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama Pasien");
        contentPane.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelSpesialis.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis.setText("Jenis Kelamin");
        contentPane.add(labelSpesialis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtUsia.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 39));

        btnSimpan.setBackground(new java.awt.Color(21, 25, 28));
        btnSimpan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Tambah");
        btnSimpan.setBorder(null);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        contentPane.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 109, 49));

        btnEdit.setBackground(new java.awt.Color(21, 25, 28));
        btnEdit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Ubah");
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        contentPane.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 109, 49));

        txtKamar.setBackground(new java.awt.Color(255, 255, 255));
        txtKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKamarKeyReleased(evt);
            }
        });
        contentPane.add(txtKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 310, 39));

        labelCari.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        labelCari.setForeground(new java.awt.Color(255, 255, 255));
        labelCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCari.setText("Id Kamar");
        contentPane.add(labelCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 40));

        cboJK.setBackground(new java.awt.Color(255, 255, 255));
        cboJK.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cboJK.setForeground(new java.awt.Color(21, 25, 28));
        cboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        contentPane.add(cboJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, 40));

        labelSpesialis1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis1.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis1.setText("Usia Pasien");
        contentPane.add(labelSpesialis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnHapus.setBackground(new java.awt.Color(21, 25, 28));
        btnHapus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.setOpaque(true);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        contentPane.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, 50));

        btnClear.setBackground(new java.awt.Color(21, 25, 28));
        btnClear.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setOpaque(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        contentPane.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 110, 50));

        txtNoTelp.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 250, 39));

        labelSpesialis2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis2.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis2.setText("Alamat");
        contentPane.add(labelSpesialis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        labelSpesialis3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSpesialis3.setForeground(new java.awt.Color(255, 255, 255));
        labelSpesialis3.setText("No Telepon");
        contentPane.add(labelSpesialis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtaAlamat.setBackground(new java.awt.Color(255, 255, 255));
        txtaAlamat.setColumns(20);
        txtaAlamat.setRows(5);
        jScrollPane1.setViewportView(txtaAlamat);

        contentPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 250, -1));

        jScrollPane2.setBackground(new java.awt.Color(35, 40, 44));
        jScrollPane2.setBorder(null);

        tbPasien.setForeground(new java.awt.Color(0, 0, 0));
        tbPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "Usia", "Jenis Kelamin", "No Telp", "Alamat"
            }
        ));
        tbPasien.setToolTipText("");
        tbPasien.setOpaque(false);
        tbPasien.setSelectionForeground(new java.awt.Color(21, 25, 28));
        tbPasien.setShowGrid(true);
        tbPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPasien);

        contentPane.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 450, 310));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(35,40,44));

        jScrollPane3.setBackground(new java.awt.Color(35, 40, 44));
        jScrollPane3.setBorder(null);

        tbKamar.setForeground(new java.awt.Color(0, 0, 0));
        tbKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "kode_kamar", "id_pasien", "status"
            }
        ));
        tbKamar.setToolTipText("");
        tbKamar.setOpaque(false);
        tbKamar.setSelectionForeground(new java.awt.Color(21, 25, 28));
        tbKamar.setShowGrid(true);
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbKamar);

        contentPane.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 450, 210));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(35,40,44));

        background.add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 820, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemSidebar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar3MouseClicked
        new dokter().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar3MouseClicked

    private void itemSidebar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar1MouseClicked
        new pasien().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar1MouseClicked

    private void itemSidebar0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar0MouseClicked
        // 200
        if(sidePaneHidden == false) {
            sidePane.setBounds(sidePane.getX(), sidePane.getY(), 72, sidePane.getHeight());
            contentPane.setBounds(contentPane.getX() - 72, contentPane.getY(), contentPane.getWidth() + 72 , contentPane.getHeight());
            sidePaneHidden = true;
        }
        else {
            sidePane.setBounds(sidePane.getX(), sidePane.getY(), 200, sidePane.getHeight());
            contentPane.setBounds(contentPane.getX() + 72, contentPane.getY(), contentPane.getWidth() - 72 , contentPane.getHeight());
            sidePaneHidden = false;
        }
    }//GEN-LAST:event_itemSidebar0MouseClicked

    private void itemSidebar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar4MouseClicked
        new admin().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar4MouseClicked

    private void itemSidebar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar5MouseClicked
        new login().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar5MouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int id_pasien_kmr = 0;
        try {
            String sql = "INSERT INTO pasien (nama_pasien,usia,jenis_kelamin,alamat,no_telp) VALUES ('"+txtNama.getText()+"','"+txtUsia.getText()+"','"+cboJK.getSelectedItem()+"','"+txtaAlamat.getText()+"','"+txtNoTelp.getText()+"')";
            java.sql.Connection conn=(Connection)DBconnection.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            try {
                String sql2 = "SELECT id_pasien FROM pasien ORDER BY id_pasien DESC LIMIT 1;";
                java.sql.Connection conn2=(Connection)DBconnection.configDB();
                Statement st = conn2.createStatement();
                ResultSet rs = st.executeQuery(sql2);
                while (rs.next()) {
                    id_pasien_kmr = rs.getInt("id_pasien");
                 }
                try{
                    String sql3 = "UPDATE kamar SET id_pasien = '"+id_pasien_kmr+"', status = 'Penuh' WHERE kode_kamar = '"+txtKamar.getText()+"'";
                    Connection conn3 = (Connection)DBconnection.configDB();
                    java.sql.PreparedStatement pst3 = conn3.prepareStatement(sql3);
                    pst3.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                    showTablePasien();
                    showTableKamar();
                    clean();
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String query = "UPDATE pasien SET nama_pasien = '"+txtNama.getText()+"', usia = "+txtUsia.getText()+", jenis_kelamin = '"+cboJK.getSelectedItem()+"', no_telp = '"+txtNoTelp.getText()+"', alamat = '"+txtaAlamat.getText()+"' WHERE id_pasien = '"+id_pasien+"'";
            Connection conn = (Connection)DBconnection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            showTablePasien();
            clean();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtKamarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKamarKeyReleased
        //        String sql = "SELECT * FROM dokter WHERE id_dokter LIKE '%" + fieldCari.getText() + "%' OR nama_dokter LIKE '%" + fieldCari.getText() + "%' OR spesialis LIKE '%" + fieldCari.getText() + "%'";
        //        showDataDokter(sql);
    }//GEN-LAST:event_txtKamarKeyReleased

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try{
            String query = "DELETE FROM pasien WHERE id_pasien = '"+id_pasien+"'";
            Connection conn = (Connection)DBconnection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            showTablePasien();
            clean();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Hapus Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clean();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPasienMouseClicked
       int baris = tbPasien.rowAtPoint(evt.getPoint());
        id_pasien =   tbPasien.getValueAt(baris, 0).toString();
        String nama =   tbPasien.getValueAt(baris, 1).toString();
        txtNama.setText(nama);
        String usia =   tbPasien.getValueAt(baris, 2).toString();
        txtUsia.setText(usia);
        String jk =   tbPasien.getValueAt(baris, 3).toString();
        cboJK.setSelectedItem(jk);
        String noTelp =   tbPasien.getValueAt(baris, 4).toString();
        txtNoTelp.setText(noTelp);
        String alamat =   tbPasien.getValueAt(baris, 5).toString();
        txtaAlamat.setText(alamat);
    }//GEN-LAST:event_tbPasienMouseClicked

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        int baris = tbKamar.rowAtPoint(evt.getPoint());
        String noKamar =   tbKamar.getValueAt(baris, 0).toString();
        txtKamar.setText(noKamar);
    }//GEN-LAST:event_tbKamarMouseClicked

    private void itemSidebar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSidebar2MouseClicked
        new kamar().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemSidebar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cboJK;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel iconAdmin;
    private javax.swing.JLabel iconAdmin1;
    private javax.swing.JLabel iconDokter;
    private javax.swing.JLabel iconKamar;
    private javax.swing.JLabel iconPasien;
    private javax.swing.JLabel iconTitle;
    private javax.swing.JPanel itemSidebar0;
    private javax.swing.JPanel itemSidebar1;
    private javax.swing.JPanel itemSidebar2;
    private javax.swing.JPanel itemSidebar3;
    private javax.swing.JPanel itemSidebar4;
    private javax.swing.JPanel itemSidebar5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelMenu0;
    private javax.swing.JLabel labelMenu1;
    private javax.swing.JLabel labelMenu2;
    private javax.swing.JLabel labelMenu3;
    private javax.swing.JLabel labelMenu4;
    private javax.swing.JLabel labelMenu5;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelSpesialis;
    private javax.swing.JLabel labelSpesialis1;
    private javax.swing.JLabel labelSpesialis2;
    private javax.swing.JLabel labelSpesialis3;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable tbKamar;
    private javax.swing.JTable tbPasien;
    private javax.swing.JTextField txtKamar;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtUsia;
    private javax.swing.JTextArea txtaAlamat;
    // End of variables declaration//GEN-END:variables
}
